# Pull Requestがオープン、リオープン、ソースが更新された時に起動

on:
  pull_request:
    types: [opened, reopened, synchronized]

jobs:

  prepare:
    runs-on: ubuntu-latest

    outputs:
      head_ref: ${{ steps.get_head_ref.outputs.head_ref }}

    steps:

    # ビルド対象のブランチ名を取得
    - name: Get Head
      id: get_head_ref
      run: |
        res=$(curl -X GET \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.CI_PAT }}" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})
        head_ref=$(echo $res | tr -d '[:cntrl:]' | jq -r '.head.ref')
        echo "::set-output name=head_ref::${head_ref}"


  build:
    needs: prepare
    runs-on: macos-latest

    env:
      TZ: 'Asia/Tokyo'

    # prepareジョブでの判定結果がtrueのときのみ実行
    if: needs.prepare.outputs.triggered == 'true'

    steps:

      # Xcode12.0.1が使用不可なので、暫定で12.4を使う
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
      - name: Show Xcode version
        run: xcodebuild -version

      # iPadリポジトリをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.prepare.outputs.head_ref }}
          path: ipad
          fetch-depth: 0

      # Cocoa Pods
      - name: Pod Install
        run: pod install

      # デバッグビルド
      - name: Build
        run: xcodebuild -sdk iphonesimulator -configuration Debug build