# AppStore申請作業時の(release→masterマージ用PR作成アクション)
name: git-pr-release
on:
  workflow_dispatch:

jobs:
  git-pr-release:
    env:
     PRODUCTION: master 
     STAGING: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install --no-document git-pr-release
      - run: git-pr-release --squashed
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{ env.PRODUCTION }} 
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ env.STAGING }}
          GIT_PR_RELEASE_LABELS: AppStore申請ワークフロー発火
          # 独自フォーマット使用したいときはテンプレートファイルを修正する
          GIT_PR_RELEASE_TEMPLATE: .github/git-pr-release.erb
          TZ: Asia/Tokyo
