name: SPIDERPLUS-webのiOSアプリ用version.json更新処理
on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'SPIDERPLUS-webリポジトリのブランチ名'
        required: true
        default: 'master'
      ipad_version:
        description: 'S+iPad version (例: 1337000.64.0.0)'
        required: false
        default: ''
      iphone_version:
        description: 'S+iPhone version (例: 243401.63.1)'
        required: false
        default: ''
      koco_ipad_version:
        description: 'KOCoチェック iPad version (例: 1.0.5.66)'
        required: false
        default: ''
      koco_iphone_version:
        description: 'KOCoチェック iPhone version (例: 3.0.0.55)'
        required: false
        default: ''

jobs:
  update_version_json_for_SPIDERPLUS-web:
    runs-on: [self-hosted, MacStudio]
    env:
     base_branch: ${{ github.event.inputs.base_branch }} 
     checkout_owner_name: spiderplus
     checkout_repo_name: SPIDERPLUS-web
     update_filePath: web/version.json
     ipad_version: ${{ github.event.inputs.ipad_version }}
     iphone_version: ${{ github.event.inputs.iphone_version }}
     koco_ipad_version: ${{ github.event.inputs.koco_ipad_version }}
     koco_iphone_version: ${{ github.event.inputs.koco_iphone_version }}
    steps:
    - name: rm repo dir
      run: |
        if [ -d "SPIDERPLUS-web" ]; then
          rm -rf SPIDERPLUS-web
        fi
    - name: Clone SPIDERPLUS-web
      run: git clone https://${{ secrets.PAT }}@github.com/${{ env.checkout_owner_name }}/${{ env.checkout_repo_name }}.git -b ${{ env.base_branch }}

    - name: Get current date and time
      id: current-time
      run: echo "DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Create new branch
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
          cd ${{ env.checkout_repo_name }}
          git checkout -b update-${{ env.DATE }}/feature
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Update ipad version
      if: ${{ env.ipad_version != '' }}
      run: |
         cd ${{ env.checkout_repo_name }}
         jq '.SpiderPlus = "${{ env.ipad_version }}"' ${{ env.update_filePath }} > tmp.json && mv tmp.json ${{ env.update_filePath }} 
         cat ${{ env.update_filePath }}

    - name: Update iphone version
      if: ${{ env.iphone_version != '' }}
      run: |
         cd ${{ env.checkout_repo_name }}
         jq '.SpiderPlus_iPhone = "${{ env.iphone_version }}"' ${{ env.update_filePath }} > tmp.json && mv tmp.json ${{ env.update_filePath }} 
         cat ${{ env.update_filePath }}

    - name: Update KOCo ipad version
      if: ${{ env.koco_ipad_version != '' }}
      run: |
         cd ${{ env.checkout_repo_name }}
         jq '.konoikeSP = "${{ env.koco_ipad_version }}"' ${{ env.update_filePath }} > tmp.json && mv tmp.json ${{ env.update_filePath }} 
         cat ${{ env.update_filePath }}

    - name: Update KOCo iPhone version
      if: ${{ env.koco_iphone_version != '' }}
      run: |
         cd ${{ env.checkout_repo_name }}
         jq '.konoikeSP_iPhone = "${{ env.koco_iphone_version }}"' ${{ env.update_filePath }} > tmp.json && mv tmp.json ${{ env.update_filePath }} 
         cat ${{ env.update_filePath }}

    - name: Commit and push changes
      env:
         GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
         cd ${{ env.checkout_repo_name }}
         git add ${{ env.update_filePath }}
         git commit -m "Update web/version.json"
         git push origin update-${{ env.DATE }}/feature

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
         curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
         -d '{"title": "Update web/version.json", "body": "This PR updates web/version.json file.", "head": "update-${{ env.DATE }}/feature", "base": "${{ env.base_branch }}"}' \
         https://api.github.com/repos/${{ env.checkout_owner_name }}/${{ env.checkout_repo_name }}/pulls
